import type { Diagnostic } from "typescript";
import * as tstl from "typescript-to-lua";
import { minify } from "html-minifier-terser";
import { watch } from "node:fs";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const WATCH = process.argv.includes("--watch");

/** Compiles JSX templates into a generated TypeScript module with string constants. */
async function compileTemplates() {
  // Dynamic import to avoid TSTL picking up JSX files
  const { PageShell, AppFragment } = require("./src/web/template.tsx");

  // XHTML-safe minification: keep attribute quotes and self-closing slashes
  const minifyHtml = (html: string) =>
    minify(html, {
      collapseWhitespace: true,
      removeComments: true,
      minifyCSS: true,
      minifyJS: true,
      keepClosingSlash: true,
    });

  // No DOCTYPE -SL HTTP-in serves as XHTML, which rejects <!DOCTYPE html>
  const shell = await minifyHtml(PageShell() as string);
  const app = await minifyHtml(AppFragment() as string);

  const content = [
    "// Auto-generated by build.ts -do not edit",
    `export const PAGE_SHELL = ${JSON.stringify(shell)};`,
    `export const APP_FRAGMENT = ${JSON.stringify(app)};`,
    "",
  ].join("\n");

  writeFileSync(resolve("src/patcher/template.ts"), content);
}

function reportDiagnostics(diagnostics: readonly Diagnostic[]) {
  let hasErrors = false;

  for (const diagnostic of diagnostics) {
    // TSTL warns about luaBundle + inline but it's harmless
    if (String(diagnostic.messageText).includes("luaBundle")) {
      continue;
    }

    const msg = String(diagnostic.messageText);

    if (diagnostic.category === 0) {
      console.error("error:", msg);
      hasErrors = true;
    } else if (diagnostic.category === 1) {
      console.warn("warning:", msg);
    }
  }

  return hasErrors;
}

async function build() {
  let hasErrors = false;

  // Step 1: Compile JSX templates to string constants
  await compileTemplates();

  // Step 2: Patcher bundle
  const patcherResult = tstl.transpileProject("tsconfig.json", {
    luaBundle: "patcher.slua",
    luaBundleEntry: resolve("src/patcher/index.ts"),
  });

  if (reportDiagnostics(patcherResult.diagnostics)) {
    hasErrors = true;
  }

  // Bootstrap standalone
  const bootstrapResult = tstl.transpileFiles([resolve("src/bootstrap.ts")], {
    rootDir: resolve("src"),
    outDir: resolve("dist"),
    target: 99, // ESNext
    module: 99, // ESNext
    strict: true,
    moduleDetection: 3, // Force
    skipLibCheck: true,
    types: ["@typescript-to-lua/language-extensions", "@gwigz/slua-types"],
    luaTarget: tstl.LuaTarget.Luau,
    luaLibImport: tstl.LuaLibImportKind.Inline,
    extension: "slua",
    luaPlugins: [{ name: "@gwigz/slua-tstl-plugin" }],
  } as tstl.CompilerOptions);

  if (reportDiagnostics(bootstrapResult.diagnostics)) {
    hasErrors = true;
  }

  if (hasErrors) {
    return false;
  }

  console.log("Built dist/patcher.slua + dist/bootstrap.slua");

  return true;
}

await build();

if (WATCH) {
  console.log("Watching src/ for changes...");

  watch(resolve("src"), { recursive: true }, (_event: string, filename: string | null) => {
    if (filename && (filename.endsWith(".ts") || filename.endsWith(".tsx"))) {
      console.log(`\nChanged: ${filename}`);
      build();
    }
  });
}
